### ISSUE TITLE
Module tree structure makes docs difficult to navigate

### ISSUE THREAD

**Issue by vkkoskie** [parallaxsecond/rust-cryptoki#55]
The overall structure of the cryptoki crate's module tree consists of several relatively long branches with often empty intermediate modules. The actual content is largely buried on distant leaves in counterintuitive locations (e.g., Session declared among data types). When I first encountered this crate, I genuinely assumed someone was just reserving the name and it was mostly empty because the places I assumed things would be (e.g., definitions of object types) were empty. That's a shame, because it exists for the same reason I was looking in the first place: the current pkcs11 crate isn't idiomatic and exposes an unsafe, easy to misuse interface.

This crate shows a lot of promise toward addressing that problem, but its documentation structure (which is a direct result of its internal structure) is (IMO) a serious barrier to it being adopted widely.

I'll be submitting a PR shortly that attempts to address this issue.

**Comment by hug-dev** [comment]
Thanks a lot for the feedback!
Agree that the documentation does feel weird to browse and sometimes you have to go pretty far to find what you need. I usually solve this problem by using the very good search bar to directly go for what I need 😄 

The file names and directory structure is not random though! It is made to exactly mirror the specification [contents](http://docs.oasis-open.org/pkcs11/pkcs11-base/v2.40/pkcs11-base-v2.40.html).

In `cryptoki/src`:

- `functions` maps to section 5 "Functions", all of the `functions` files are a 1-1 mapping with a 5.x subsection
- `objects` maps to section 4 "Objects"
- `types` maps to section 3 "General data types". Its `mechanism` folder is the expansion of section 3.5 with what is in the [Current Mechanisms Specification](http://docs.oasis-open.org/pkcs11/pkcs11-curr/v2.40/pkcs11-curr-v2.40.html)

The advantage of this is that it's easy for anyone to contribute to this crate as they just have to follow the same structure as the specification.

Happy to discuss a new structure or other solutions to make the documentation easier to read. We could maybe re-surface some useful types to higher level so that they show sooner in the documentation (and can be used with a shorter path).

We should also be more clear on why this structure has been chosen.

Also, maybe it is because we don't have enough top-level examples to show how to get started that one has to browse through the documentation to look what they want?

**Comment by vkkoskie** [comment]
Thanks for these insights. I do find them odd though.

One of the stated design goals of this project is to be idomatic in Rust, and I was hoping that had precedence over strict adherence to a standard that is very much tied to C and its idioms. For instance, there are several helper methods already in the crate that don't map directly to functions in the PKCS11 API, which I think is great. They provide abstraction over details that shouldn't be a concern for users of the crate.

> The file names and directory structure is not random though! It is made to exactly mirror the specification contents.

I recognized (or guessed) that this was the case. This seems like a perfectly reasonable thing for the cryptoki-sys crate to do, but I would disagree that it should be imposed on an abstraction layer.

> The advantage of this is that it's easy for anyone to contribute to this crate as they just have to follow the same structure as the specification.

Strong (but friendly!) disagree here. The design of a public API should be guided by the end users' needs, not its developer(s). In Rust, these are, for better or for worse, strongly linked. That is, in C, it's fairly easy to have one internal structure for developers to approach and another structure for the public API. In Rust, it's possible but takes a bit more work. Some examples of this are in first PR commit, where the internal structure is guarded by `pub(crate)` markers and the outer structure is re-exported through a proxy tree. I wouldn't go that route in the long term though because it's difficult to maintain (hence additional PR commits that make the proxy tree the real one).

As for the PR, I didn't expect it to be merged without discussion, and even if you were 100% on board with restructuring, I doubt I'd get the exact placement and naming on a first attempt. Nevertheless, I think running `cargo rustdoc --open` will show what I would consider to be in the right direction overall. Specifically, groupings of and within modules should provide conceptual linkage and be guided by ease-of-use ideals (rather than the spec, which serves a different set of goals).

**Comment by vkkoskie** [comment]
I'll also add that I have an interest in submitting more PRs to address smaller issues like excessive `pub` but wanted to make this one a priority because it will create merge conflicts for anything submitted along side it.

**Comment by hug-dev** [comment]
Thanks for the explanation. I think what you wrote made sense, specially the fact that we should make it easy for the users of this crate for it to become popular. As you said, this is an abstraction so we should be able to define our own structure of modules.
I would then be in favour of shuffling the tree and finding what is best. As this crate is still quite new and pre `1.0.0` I would say it should be fine to make heavy breaking changes.

We could take a look at everything that is there now and work from scratch to find what would be the best structure. I can have a look later on this following weeks but it would also be nice to have the opinions of contributors @anta5010 @ionut-arm @mjb3279 @wiktor-k

**Comment by mjb3279** [comment]
Hi @vkkoskie!  First off, I want to thank you for splitting your PR into easily digestible chunks.  Definitely made it easier to read through and to understand your reasoning.

Overall, I think I'm in agreement with your proposed changes.  I especially appreciate the flattening of the module tree.

I think your insight on how the crate should be structured is extremely helpful (especially to someone like myself who is still relatively new to Rust).

I have no good arguments against merging in this PR.

**Comment by vkkoskie** [comment]
I agree that it could go. I also think functions should be factored into the session and context impls. But I was already a random stranger on the internet rolling in with major revisions, so I didn't want to be _too_ ambitious in my initial proposal. :grin:

**Comment by mjb3279** [comment]
I'm in agreement with that.  I say go for it.

**Comment by ionut-arm** [comment]
Hey! Thanks for raising this issue and the corresponding PR - I've not reviewed the PR yet, but I'll take some time tomorrow to go through it.

I think you touch on an important point - we, as developers of this crate, very rarely go to actually look on docs.rs and see how things would look for someone just starting off with the crate, which is a pity. I had a skim just now and it is quite hilarious to see the empty modules, I don't think I was even aware they were public. What @hug-dev said above is true here and is also true of our [`tss-esapi`](https://github.com/parallaxsecond/rust-tss-esapi) crate - we've tried to structure the crate around the spec. Hugues said:

> The advantage of this is that it's easy for anyone to contribute to this crate as they just have to follow the same structure as the specification.

but my position goes further than that - yes, we do make PKCS11 (or the TSS stack, in the case of the other crate) safer, harder to misuse, and Rust'ier, but the crate still exists at a very low level. As a user, you should really be comfortable navigating the spec and understanding its finer points/limitations/... in order to make proper use of this library. Or, at least, that's what I think we had in mind when we started working on these crates - we certainly didn't build them with an idea that people could just look at our code documentation and know how to use PKCS11 => users should be comfortable with the spec, and structuring the code like the spec would actually help them.

But I think you're right, we should try at least to make the documentation more palatable to people completely new to PKCS11. I think this would need two changes, one of which is what you're trying to do in your PR - restructuring the API. The second would be to expand documentation to guide anyone new to PKCS11 in the right direction, both in terms of how our crate works, but also pointing them to the official documentation.
