### ISSUE TITLE
`get_attributes()` with AttributeType::Class fails for private key with YubiHSM2 Nano

### ISSUE THREAD

**Issue by ximon18** [parallaxsecond/rust-cryptoki#76]
Hi,

Before I start asking questions again first let me say thanks for the `cryptoki` crate!

When I migrated my simple [keyls](https://github.com/ximon18/keyls) tool from the Rust `pkcs11` crate to the `cryptoki` crate I encountered a strange problem that I hadn't had before. When fetching attributes for a key I can request the class attribute but only for a public key, when doing so for a public key I get a "Feature not supported" error.

See the [old code](https://github.com/ximon18/keyls/blob/1ae512cbbd5ef41b7081c89a40c0e3f59edb576c/src/pkcs11client.rs#L43) vs the [new code](https://github.com/ximon18/keyls/blob/main/src/pkcs11client.rs#L67).

Am I doing something wrong?

Thanks,

Ximon

**Comment by ionut-arm** [comment]
Hi,

Hmm, this sounds somewhat familiar. Have you tried with the tip of `main` as well? I know it's a bit of a hassle to go from 0.2.0 to that, but it might be fixed. Otherwise I'll have to dig a bit. I know we had some problems related to attribute values that we didn't support, but I thought only vendor-specific values are left in that state now.

**Comment by ximon18** [comment]
Ah, I thought that was using the tip of main, my apologies I will check.

**Comment by ximon18** [comment]
Indeed it works fine with the tip of main, my apologies for that.

**Comment by ionut-arm** [comment]
Glad to hear!!
