### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by moh-eulith** [parallaxsecond/rust-cryptoki#93]
I noticed the tests are `#[serial]`. How do I use this library in a multi-threaded Rust app safely? It would be nice to be able to amortize the cost of slot/token/login/key stuff.

**Comment by mjb3279** [comment]
The tests run serially because each test will initialize the underlying PKCS#11 library utilizing the `C_Initialize` function call.  It is an error, by spec, to call `C_Initialize` more than once.  At the completion of the test, when the `Pkcs11` object is dropped, the `C_Finalize` function is called, allowing the next test to run `C_Initialize` without error.

You can use this library in a multi-threaded environment provided that you:

1. Only have one instance of the `Pkcs11` object
2. Each thread uses their own `Session` object (or if you do use a single `Session` object, only one thread may access it at a time).

You can read the [PKCS#11 User's Guide](http://docs.oasis-open.org/pkcs11/pkcs11-ug/v2.40/cn02/pkcs11-ug-v2.40-cn02.html) for more information on how to use a PKCS#11 library in a multi-threaded environment.
